import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "@/Context/AuthProvider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//  this is not neccesat y to  keep that the layout.jsx is conpulosry
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <AuthProvider>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
      </AuthProvider>
    </html>
  );
}
